### ISSUE TITLE
Input unrecognised

### ISSUE THREAD

**Issue by flamebeard** [JustJeeCode/Simple-Black-Jack-Game#1]
```ehurst@IT8964L MINGW64 /c/Users/ehurst/Github/Simple-Black-Jack-Game (master)
$ python main.py
Dealers deck: [x, 10]
Your deck: [4, 7]

Do you chose to "Hit" or "Stay"? [H/S]

>>> h
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    main()
  File "main.py", line 92, in main
    player_hit_stay()
  File "main.py", line 12, in player_hit_stay
    hit_or_stay = input("\nDo you chose to \"Hit\" or \"Stay\"? [H/S]\n\n>>> ")
  File "<string>", line 1, in <module>
NameError: name 'h' is not defined

ehurst@IT8964L MINGW64 /c/Users/ehurst/Github/Simple-Black-Jack-Game (master)
$ python main.py
Dealers deck: [x, 4]
Your deck: [2, 1]

Do you chose to "Hit" or "Stay"? [H/S]

>>> hit
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    main()
  File "main.py", line 92, in main
    player_hit_stay()
  File "main.py", line 12, in player_hit_stay
    hit_or_stay = input("\nDo you chose to \"Hit\" or \"Stay\"? [H/S]\n\n>>> ")
  File "<string>", line 1, in <module>
NameError: name 'hit' is not defined```

**Comment by JustJeeCode** [comment]
Thanks, Flamebeard for the issue I'm pretty sure the bug has been fixed!

**Comment by flamebeard** [comment]
Still isn't working for me :/

```
ehurst@IT8964L MINGW64 /c/Users/ehurst/Github/Simple-Black-Jack-Game (master)
$ python main.py
Dealers deck: [x, 5]
Your deck: [10, 2]

Do you chose to "Hit" or "Stay"? [H/S]

>>> H
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 100, in main
    player_hit_stay()
  File "main.py", line 13, in player_hit_stay
    hit_or_stay = input("\nDo you chose to \"Hit\" or \"Stay\"? [H/S]\n\n>>> ")
  File "<string>", line 1, in <module>
NameError: name 'H' is not defined

ehurst@IT8964L MINGW64 /c/Users/ehurst/Github/Simple-Black-Jack-Game (master)
$ python main.py
Dealers deck: [x, 4]
Your deck: [2, 8]

Do you chose to "Hit" or "Stay"? [H/S]

>>> h
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 100, in main
    player_hit_stay()
  File "main.py", line 13, in player_hit_stay
    hit_or_stay = input("\nDo you chose to \"Hit\" or \"Stay\"? [H/S]\n\n>>> ")
  File "<string>", line 1, in <module>
NameError: name 'h' is not defined
```

**Comment by flamebeard** [comment]
Looks like you have to wrap your answer in double quotes 

```
ehurst@IT8964L MINGW64 /c/Users/ehurst/Github/Simple-Black-Jack-Game (master)
$ python main.py
Dealers deck: [x, 8]
Your deck: [1, 6]

Do you chose to "Hit" or "Stay"? [H/S]

>>> "h"
Dealers deck: [x, 8]
Your deck: [1, 6, 8]

Do you chose to "Hit" or "Stay"? [H/S]
```
